// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var level = Level.FromJson(jsonString);

using System.Numerics;
using Raylib_cs;

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using J = Newtonsoft.Json.JsonPropertyAttribute;
    using R = Newtonsoft.Json.Required;
    using N = Newtonsoft.Json.NullValueHandling;

    public partial class Level
    {
        [J("__header__")]        public Header Header { get; set; }                     
        [J("identifier")]        public string Identifier { get; set; }                 
        [J("iid")]               public Guid Iid { get; set; }                          
        [J("uid")]               public long Uid { get; set; }                          
        [J("worldX")]            public long WorldX { get; set; }                       
        [J("worldY")]            public long WorldY { get; set; }                       
        [J("worldDepth")]        public long WorldDepth { get; set; }                   
        [J("pxWid")]             public long PxWid { get; set; }                        
        [J("pxHei")]             public long PxHei { get; set; }                        
        [J("__bgColor")]         public string BgColor { get; set; }                    
        [J("bgColor")]           public object LevelBgColor { get; set; }               
        [J("useAutoIdentifier")] public bool UseAutoIdentifier { get; set; }            
        [J("bgRelPath")]         public object BgRelPath { get; set; }                  
        [J("bgPos")]             public object LevelBgPos { get; set; }                 
        [J("bgPivotX")]          public double BgPivotX { get; set; }                   
        [J("bgPivotY")]          public double BgPivotY { get; set; }                   
        [J("__smartColor")]      public string SmartColor { get; set; }                 
        [J("__bgPos")]           public object BgPos { get; set; }                      
        [J("externalRelPath")]   public object ExternalRelPath { get; set; }            
        [J("fieldInstances")]    public List<object> FieldInstances { get; set; }       
        [J("layerInstances")]    public List<LayerInstance> LayerInstances { get; set; }
        [J("__neighbours")]      public List<object> Neighbours { get; set; }           
    }

    public partial class Header
    {
        [J("fileType")]   public string FileType { get; set; }  
        [J("app")]        public string App { get; set; }       
        [J("doc")]        public Uri Doc { get; set; }          
        [J("schema")]     public Uri Schema { get; set; }       
        [J("appAuthor")]  public string AppAuthor { get; set; } 
        [J("appVersion")] public string AppVersion { get; set; }
        [J("url")]        public Uri Url { get; set; }          
    }

    public partial class LayerInstance
    {
        [J("__identifier")]       public string Identifier { get; set; }           
        [J("__type")]             public string Type { get; set; }                 
        [J("__cWid")]             public long CWid { get; set; }                   
        [J("__cHei")]             public long CHei { get; set; }                   
        [J("__gridSize")]         public long GridSize { get; set; }               
        [J("__opacity")]          public long Opacity { get; set; }                
        [J("__pxTotalOffsetX")]   public long PxTotalOffsetX { get; set; }         
        [J("__pxTotalOffsetY")]   public long PxTotalOffsetY { get; set; }         
        [J("__tilesetDefUid")]    public long? TilesetDefUid { get; set; }         
        [J("__tilesetRelPath")]   public string TilesetRelPath { get; set; }       
        [J("iid")]                public Guid Iid { get; set; }                    
        [J("levelId")]            public long LevelId { get; set; }                
        [J("layerDefUid")]        public long LayerDefUid { get; set; }            
        [J("pxOffsetX")]          public long PxOffsetX { get; set; }              
        [J("pxOffsetY")]          public long PxOffsetY { get; set; }              
        [J("visible")]            public bool Visible { get; set; }                
        [J("optionalRules")]      public List<object> OptionalRules { get; set; }  
        [J("intGridCsv")]         public List<long> IntGridCsv { get; set; }       
        [J("autoLayerTiles")]     public List<Tile> AutoLayerTiles { get; set; }   
        [J("seed")]               public long Seed { get; set; }                   
        [J("overrideTilesetUid")] public object OverrideTilesetUid { get; set; }   
        [J("gridTiles")]          public List<Tile> GridTiles { get; set; }        
        [J("entityInstances")]    public List<object> EntityInstances { get; set; }
    }

    public partial class Tile
    {
        [J("px")]  public List<long> Px { get; set; } 
        [J("src")] public List<long> Src { get; set; }
        [J("f")]   public long F { get; set; }        
        [J("t")]   public long T { get; set; }        
        [J("d")]   public List<long> D { get; set; }  
        [J("a")]   public long A { get; set; }

        public void Draw(Texture2D tileset){
            const int tileSize = 16;
            bool flipX = (F & 1) != 0;
            bool flipY = (F & 2) != 0;
            Rectangle dest = new(Px[0], Px[1],tileSize,tileSize);
            Rectangle src = new(Src[0], Src[1],flipX? -tileSize: +tileSize,flipY?-tileSize:+tileSize);
            Raylib.DrawTexturePro(tileset, src, dest, Vector2.Zero, 0f, Color.White);
            
        }
    }

    public partial class Level
    {
        public static Level FromJson(string json) => JsonConvert.DeserializeObject<Level>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Level self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
